<%@ Page Language="C#" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Report Generator</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .form-group { margin: 15px 0; }
        label { display: inline-block; width: 150px; font-weight: bold; }
        input[type="text"] { width: 300px; padding: 5px; }
        button { padding: 8px 15px; background-color: #007bff; color: white; border: none; cursor: pointer; }
        button:hover { background-color: #0056b3; }
        .result { margin-top: 20px; padding: 10px; border: 1px solid #ddd; background-color: #f9f9f9; }
    </style>
</head>
<body>
    <h1>Report Generator</h1>

    <form id="form1" runat="server">
        <div class="form-group">
            <label for="txtReportName">Report Name:</label>
            <input type="text" id="txtReportName" runat="server" placeholder="Enter report name" />
        </div>

        <div class="form-group">
            <label for="txtReportDate">Date:</label>
            <input type="text" id="txtReportDate" runat="server" placeholder="YYYY-MM-DD" />
        </div>

        <div class="form-group">
            <asp:Button ID="btnGenerate" runat="server" Text="Generate Report" OnClick="btnGenerate_Click" />
        </div>

        <div class="result">
            <asp:Label ID="lblResult" runat="server"></asp:Label>
        </div>

        <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
    </form>

    <hr />
    <h2>Technical Notes:</h2>
    <ul>
        <li>This page uses ASP.NET ViewState to maintain state</li>
        <li>ViewState is signed with HMACSHA256 and encrypted with AES</li>
        <li>An attacker who knows the machineKey can forge a valid ViewState</li>
        <li>The ViewState is transmitted in the __VIEWSTATE hidden field</li>
        <li>NOTE: __VIEWSTATEGENERATOR is auto-generated by ASP.NET</li>
    </ul>
</body>
</html>

<script runat="server">
protected void btnGenerate_Click(object sender, EventArgs e)
{
    try
    {
        string reportName = Request["txtReportName"];
        string reportDate = Request["txtReportDate"];

        if (string.IsNullOrWhiteSpace(reportName))
        {
            lblError.Text = "Report name is required.";
            return;
        }

        if (string.IsNullOrWhiteSpace(reportDate))
        {
            lblError.Text = "Date is required.";
            return;
        }

        // ============================================
        // VULNERABILITY: ViewState Deserialization
        // ============================================
        // 這個頁面本身沒有明確的反序列化代碼，但 ASP.NET 框架本身會：
        //
        // 1. 在頁面 postback 時自動解析 __VIEWSTATE 參數
        // 2. 使用 ObjectStateFormatter 將其反序列化回 .NET 物件
        // 3. 如果 ViewState 簽章和加密都正確，會信任該物件
        //
        // 如果攻擊者已從 web.config 中讀到 machineKey（透過 Stage 1 的 LFI 漏洞）
        // 就能用 ysoserial.net 生成惡意 ViewState，達成 RCE。
        // ============================================

        string report = "Report: " + reportName + "\nDate: " + reportDate + "\nGenerated at: " + DateTime.Now;
        lblResult.Text = "<pre>" + System.Web.HttpUtility.HtmlEncode(report) + "</pre>";
        lblError.Text = "";
    }
    catch (Exception ex)
    {
        lblError.Text = "Error: " + ex.Message;
    }
}
</script>
